Bootstrap: docker
From: ubuntu:20.04

%setup
  mkdir ${SINGULARITY_ROOTFS}/common
  cp -t ${SINGULARITY_ROOTFS}/common -r ../common/src ../common/lib.zip ../common/Makefile

%post
  apt-get update

  apt-get -y install cmake
  apt-get -y install g++
  apt-get -y install libboost-all-dev
  apt-get -y install libgmp-dev
  apt-get -y install make
  apt-get -y install unzip

  make --directory=/common htb OPT=-Ofast

%help
  This is a container for the planning tool HTB.

%runscript
  /common/htb "$@"
