Bootstrap: docker
From: ubuntu:20.04

%setup
  mkdir ${SINGULARITY_ROOTFS}/addmc
  cp -t ${SINGULARITY_ROOTFS}/addmc -r ../addmc/src ../addmc/lib.zip ../addmc/Makefile

%post
  apt-get update

  apt-get -y install cmake
  apt-get -y install g++
  apt-get -y install libboost-all-dev
  apt-get -y install libgmp-dev
  apt-get -y install make
  apt-get -y install unzip

  make --directory=/addmc dmc OPT=-Ofast

%help
  This is a container for the execution tool DMC.

%runscript
  /addmc/dmc "$@"
